CREATE DATABASE QuanLyCuaHangTraChanh
USE QuanLyCuaHangTraChanh
GO

--KICH THUOC
CREATE TABLE KICHTHUOC(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	MaKT VARCHAR(30) UNIQUE,
	TenKT NVARCHAR(50) DEFAULT NULL,
	Gia DECIMAL(20,0) DEFAULT 0,
	TrangThai INT DEFAULT 0
)
GO
--SAN PHAM
CREATE TABLE SANPHAM (
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	IdKT UNIQUEIDENTIFIER,
	IdDM UNIQUEIDENTIFIER,
	MaSP VARCHAR(30) UNIQUE, 
	TenSP NVARCHAR(50) DEFAULT NULL,
	GiaNhap DECIMAL(20,0) DEFAULT 0,
	GiaBan DECIMAL(20,0) DEFAULT 0,
	SoLuongTon int,
	MoTa nvarchar(50),
	TrangThai INT DEFAULT 0
)
GO
--Hinh Anh SP
Create table HINHANH(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	IdSanPham UNIQUEIDENTIFIER,
	TenHA NVARCHAR(50) DEFAULT NULL,
	DuongDan NVARCHAR(100),
	TrangThai INT DEFAULT 0
)
ALTER TABLE HINHANH ADD  DUONGDAN VARCHAR(100)
--DanhMuc-TheLoai
CREATE TABLE DANHMUC(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	IdTL UNIQUEIDENTIFIER,
	MaTL VARCHAR(30) UNIQUE,
	TenTL NVARCHAR(50) DEFAULT NULL,
	TrangThai INT DEFAULT 0
)
GO

--BAN
CREATE TABLE BAN(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	MaBan VARCHAR(30) DEFAULT NULL,
	TenBan Nvarchar(30),
	SoNguoi int,
	TrangThai INT DEFAULT 0
)

--KHUYEN MAI
CREATE TABLE KHUYENMAI(
	Id  UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Ma VARCHAR(20) UNIQUE,
	Ten NVARCHAR(50) DEFAULT NULL,
	NgayBatDau DATETIME DEFAULT NULL,
	NgayKetThuc DATETIME DEFAULT NULL,
	MucGiamGia DECIMAL(20,0),
	DieuKienGiamGia NVARCHAR(50) DEFAULT NULL,
	LoaiGiamGia NVARCHAR(50) DEFAULT NULL,
	TrangThai INT DEFAULT 0,
)
GO
--SPKhuyenMai
Create table SPKHUYENMAI(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	IdKM UNIQUEIDENTIFIER,
	IdSP UNIQUEIDENTIFIER,
	DonGia DECIMAL(20,0) DEFAULT 0,
	SoTienConLai DECIMAL(20,0) DEFAULT 0,
	TrangThai INT DEFAULT 0
)
--HOA DON
CREATE TABLE HOADON(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	IdNV UNIQUEIDENTIFIER,
	IdKH UNIQUEIDENTIFIER,
	IdBAN UNIQUEIDENTIFIER,
	MaHD VARCHAR(50) UNIQUE,
	NgayTao DATETIME DEFAULT NULL,
	NgayThanhToan DATETIME DEFAULT NULL,
	TongTien DECIMAL(20,0) DEFAULT 0,
	PhanTramGiamGia DECIMAL(20,0) DEFAULT 0,
	TrangThai INT DEFAULT 0
)
GO
--HOA DON CHI TIET
CREATE TABLE HOADONCHITIET(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	IdHD UNIQUEIDENTIFIER,
	IdSP UNIQUEIDENTIFIER,
	IdDa UNIQUEIDENTIFIER,
	IdDuong UNIQUEIDENTIFIER,
	SoLuong DECIMAL(20,0) DEFAULT 0, 
	DonGia DECIMAL(20,0) DEFAULT 0,
	GiaDuong DECIMAL(20,0) DEFAULT 0,
	GiaDa DECIMAL(20,0) DEFAULT 0,
	ThanhTien DECIMAL(20,0) DEFAULT 0,
	TrangThai INT DEFAULT 0
)
GO
--MUC DUONG
CREATE TABLE MUCDUONG(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	MaD VARCHAR(20) UNIQUE,
	TenD NVARCHAR(30) DEFAULT NULL,
	GiaD DECIMAL(20,0) DEFAULT 0,
	TrangThai INT DEFAULT 0
)
--MUCDA
CREATE TABLE MUCDA(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	MaD VARCHAR(20) UNIQUE,
	TenD NVARCHAR(30) DEFAULT NULL,
	GiaD DECIMAL(20,0) DEFAULT 0,
	TrangThai INT DEFAULT 0
)
--HINH THUC THANH TOAN
CREATE TABLE HINHTHUCTHANHTOAN(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	IdHD UNIQUEIDENTIFIER,
	IdNV UNIQUEIDENTIFIER,
	Ma VARCHAR(20) UNIQUE,
	NgayTao DATETIME DEFAULT NULL,
	NgaySua DATETIME DEFAULT NULL,
	LoaiHinhThanhToan NVARCHAR(50) DEFAULT NULL,
	TongTienThanhToan DECIMAL(20,0) DEFAULT 0,
	TrangThai INT DEFAULT 0
)
--NHAN VIEN
CREATE TABLE NHANVIEN(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Ma VARCHAR(20) UNIQUE,
	Ten NVARCHAR(30) DEFAULT NULL,
	GioiTinh NVARCHAR(10) DEFAULT NULL,
	NgaySinh DATE DEFAULT NULL,
	DiaChi NVARCHAR(100) DEFAULT NULL,
	Sdt VARCHAR(30) DEFAULT NULL,
	GhiChu NVARCHAR(50) DEFAULT NULL,
	MatKhau VARCHAR(MAX) DEFAULT NULL,
	TrangThai INT DEFAULT 0,
	Anh nvarchar(50) NULL,
	NgayTao DATETIME DEFAULT NULL,
	IdCV UNIQUEIDENTIFIER,
)
GO
--KHACH HANG
CREATE TABLE KHACHHANG(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Ma VARCHAR(20) UNIQUE,
	Ten NVARCHAR(30) DEFAULT NULL,
	NgaySinh DATE DEFAULT NULL,
	Sdt VARCHAR(30) DEFAULT NULL,
	DiaChi NVARCHAR(100) DEFAULT NULL,
	GioiTinh NVARCHAR(10) DEFAULT NULL,
	GhiChu NVARCHAR(50) DEFAULT NULL,
	TrangThai INT DEFAULT 0
)
GO
--CHUC VU
CREATE TABLE CHUCVU(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	MaCV VARCHAR(20) UNIQUE,
	TenCV NVARCHAR(30) DEFAULT NULL,
	GhiChu NVARCHAR(50) DEFAULT NULL,
	TrangThai INT DEFAULT 0
)



--TẠO MỐI QUAN HỆ GIỮA CÁC BẢNG
--SAN PHAM  - KICH THUOC
ALTER TABLE SANPHAM ADD FOREIGN KEY(IdKT) REFERENCES KICHTHUOC(Id)
--SAN PHAM  - DANH MUC
ALTER TABLE SANPHAM ADD FOREIGN KEY(IdDM) REFERENCES DANHMUC(Id)
--HINH ANH - SAN PHAM
ALTER TABLE HINHANH ADD FOREIGN KEY(IdSanPham) REFERENCES SANPHAM(Id)
-- SP KHUYEM MAI -- KHUYEN MAI
ALTER TABLE SPKHUYENMAI ADD FOREIGN KEY(IdKM) REFERENCES KHUYENMAI(Id)
-- SP KHUYEM MAI -- SAN PHAM
ALTER TABLE SPKHUYENMAI ADD FOREIGN KEY(IdSP) REFERENCES SANPHAM(Id)
--HOA DON - KHACH HANG
ALTER TABLE HOADON ADD FOREIGN KEY(IdKH) REFERENCES KHACHHANG(Id)
--HOA DON - NHAN VIEN
ALTER TABLE HOADON ADD FOREIGN KEY(IdNV) REFERENCES NHANVIEN(Id)
--HOA DON - BAN
ALTER TABLE HOADON ADD FOREIGN KEY(IdBAN) REFERENCES BAN(Id)
--HINH THUC THANH TOAN -NHAN VIEN
ALTER TABLE HINHTHUCTHANHTOAN ADD FOREIGN KEY(IdNV) REFERENCES NHANVIEN(Id)
--HINH THUC THANH TOAN -HOA DON
ALTER TABLE HINHTHUCTHANHTOAN ADD FOREIGN KEY(IdHD) REFERENCES HOADON(Id)
--NHAN VIEN - CHUC VU
ALTER TABLE NHANVIEN ADD FOREIGN KEY(IdCV) REFERENCES CHUCVU(Id)
--HOA DON CHI TIET -MUC DUONG
ALTER TABLE HOADONCHITIET ADD FOREIGN KEY(IdDUONG) REFERENCES MUCDUONG(Id)
--HOA DON CHI TIET -MUC DA
ALTER TABLE HOADONCHITIET ADD FOREIGN KEY(IdDA) REFERENCES MUCDA(Id)
--HOA DON CHI TIET -SAN PHAM
ALTER TABLE HOADONCHITIET ADD FOREIGN KEY(IdSP) REFERENCES SANPHAM(Id)
--HOA DON CHI TIET -HOA DON
ALTER TABLE HOADONCHITIET ADD FOREIGN KEY(IdHD) REFERENCES HOADON(Id)
-- SELF JOIN DANH MUC VS DANHMUC(THELOAI)
ALTER TABLE DANHMUC ADD FOREIGN KEY(IdTL) REFERENCES DANHMUC(Id)

drop database QuanLyCuaHangTraChanh



select * from DANHMUC
select * from SANPHAM
select * from HOADON
select * from HOADONCHITIET
select * from KICHTHUOC
select * from NHANVIEN
select * from MUCDUONG
select * from MUCDA
select * from CHUCVU
select * from KHUYENMAI
select * from SPKHUYENMAI
select * from BAN
select * from HINHANH
select * from HINHTHUCTHANHTOAN
select * from MUCDA



select idhd,mahd,sum(thanhtien) from HOADONCHITIET inner join hoadon on HOADON.Id=HOADONCHITIET.IdHD group by IdHD,MaHD

ALTER TABLE HOADONCHITIET
DROP ngay;
delete from SANPHAM
delete from HINHANH
delete from SPKHUYENMAI
delete from sanpham
delete from hoadonchitiet
delete from HOADON
delete from NHANVIEN where id='508CAEE6-4619-4EAE-856B-52E30EAF5876'
SELECT dbo.SANPHAM.MaSP, dbo.SANPHAM.TenSP, dbo.KICHTHUOC.TenKT, dbo.DANHMUC.TenTL, dbo.SANPHAM.GiaNhap, dbo.SANPHAM.GiaBan, dbo.SANPHAM.SoLuongTon, dbo.SANPHAM.MoTa, dbo.SANPHAM.TrangThai,dbo.HINHANH.DuongDan
FROM dbo.SANPHAM INNER JOIN dbo.KICHTHUOC ON dbo.SANPHAM.IdKT = dbo.KICHTHUOC.Id 
INNER JOIN dbo.DANHMUC ON dbo.SANPHAM.IdDM = dbo.DANHMUC.Id

SELECT MaHD,TenBan,MaSP,TenSP,SoLuong,GiaBan,ThanhTien FROM SANPHAM 
                                                 INNER JOIN HOADONCHITIET ON SANPHAM.ID=HOADONCHITIET.IdSP 
                                                 INNER JOIN HOADON ON HOADONCHITIET.IdHD=HOADON.Id
												 inner join BAN on BAN.Id=HOADON.IdBAN
                           delete from hoadonchitiet where id = '9CFC8FE0-47C3-45A8-A0A0-0F20FD4AC0D3'  
						   WHERE MaHD like'HD77298138'
						   delete FROM HOADONCHITIET  WHERE IDSP='8DFF5A41-9811-412A-84EC-07EE2A19A219' and idhd='F50E833E-8C46-40B4-B89F-130B329C3D33'
SELECT MaHD,HOADON.NgayTao,HOADON.NgayTao,MaSP,TenSP,ThanhTien,hoadon.TrangThai FROM SANPHAM 
                                                               INNER JOIN HOADONCHITIET ON SANPHAM.ID=HOADONCHITIET.IdSP 
                                                               INNER JOIN HOADON ON HOADONCHITIET.IdHD=HOADON.Id
 SELECT MaHD,TenBan,HOADON.NgayTao,,HOADON.NgayTao,MaSP,TenSP,ThanhTien,hoadon.TrangThai FROM SANPHAM 
                                                               INNER JOIN HOADONCHITIET ON SANPHAM.ID=HOADONCHITIET.IdSP 
                                                               INNER JOIN HOADON ON HOADONCHITIET.IdHD=HOADON.Id	
															   inner join BAN on BAN.Id=HOADON.IdBAN
SELECT MA,TEN,LOAIGIAMGIA,MUCGIAMGIAPHANTRAM,TenSP,GiaBan,SoTienConLai,TrangThai FROM KHUYENMAI 
INNER JOIN SPKHUYENMAI ON KHUYENMAI.ID=SPKHUYENMAI.IDKM 
INNER JOIN SANPHAM ON SANPHAM.Id=SPKHUYENMAI.IdSP